language: go
sudo: false

go:
  - 1.19.x

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

install:
  - go get -u golang.org/x/tools/cmd/stringer
  - go get -u golang.org/x/lint/golint

script:
  - make test
  - CARAVAN_DEBUG=0 go test -coverprofile c.out ./...
  - go clean -testcache
  - CARAVAN_DEBUG=1 go test -coverprofile c.append.out ./...
  - tail -n +2 c.append.out >> c.out

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
